<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Capturing Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target ="_blank" href="E:\Wallpaper\bike_chase.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target ="_blank" href="E:\Wallpaper\bike_chase.jpg"><img src="E:\Wallpaper\bike_chase.jpg" height=200 width=300></img></a>]]>
    </line>
    <line>
      <![CDATA[Capturing Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target ="_blank" href="E:\Wallpaper\bike_chase.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target ="_blank" href="E:\Wallpaper\bike_chase.jpg"><img src="E:\Wallpaper\bike_chase.jpg" height=200 width=300></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Basics" duration-ms="13170" started-at="2021-11-06T23:11:59 IST" finished-at="2021-11-06T23:12:12 IST">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="3578" started-at="2021-11-06T23:11:59 IST" finished-at="2021-11-06T23:12:02 IST">
      <class name="com.w2a.testcases.BankManagerLoginTest">
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:com.w2a.testcases.BankManagerLoginTest@17497425]" name="loginAsBankManager" duration-ms="3381" started-at="2021-11-06T23:11:59 IST" finished-at="2021-11-06T23:12:02 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login not Successfull]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login not Successfull
at org.testng.Assert.fail(Assert.java:99)
at com.w2a.testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$310/2116179210.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1234)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target ="_blank" href="E:\Wallpaper\bike_chase.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target ="_blank" href="E:\Wallpaper\bike_chase.jpg"><img src="E:\Wallpaper\bike_chase.jpg" height=200 width=300></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.w2a.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="8580" started-at="2021-11-06T23:12:03 IST" finished-at="2021-11-06T23:12:12 IST">
      <class name="com.w2a.testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.w2a.testcases.AddCustomerTest@72e5a8e]" name="setUp" is-config="true" duration-ms="14051" started-at="2021-11-06T23:11:45 IST" finished-at="2021-11-06T23:11:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomerTest@72e5a8e]" name="addCustomerTest" duration-ms="7993" started-at="2021-11-06T23:12:04 IST" data-provider="getData" finished-at="2021-11-06T23:12:12 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mukesh]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ambani]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[411223.0]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Customer Not Added Successfully  !!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Customer Not Added Successfully  !!!
at org.testng.Assert.fail(Assert.java:99)
at com.w2a.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$310/2116179210.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1234)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target ="_blank" href="E:\Wallpaper\bike_chase.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target ="_blank" href="E:\Wallpaper\bike_chase.jpg"><img src="E:\Wallpaper\bike_chase.jpg" height=200 width=300></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.w2a.testcases.AddCustomerTest@72e5a8e]" name="tearDown" is-config="true" duration-ms="1095" started-at="2021-11-06T23:12:12 IST" finished-at="2021-11-06T23:12:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
